steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/frontend',
      '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
      '--build-arg', 'NEXT_PUBLIC_SITE_URL=$_NEXT_PUBLIC_SITE_URL',
      '.'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend'
      - '--region'
      - 'us-central1'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/$PROJECT_ID/frontend'
substitutions:
  _NEXT_PUBLIC_API_URL: ''
  _NEXT_PUBLIC_SITE_URL: ''
